In [1]:
import pandas as pd
import numpy as np

In [2]:
file = '../../../../../../../dataframes/enigh/CONCENTRADOHOGAR/mixed/df_09.csv'

In [3]:
df = pd.read_csv(file)

In [4]:
df.shape

(1733, 120)

In [5]:
df_copy = df.copy()

In [6]:
df_copy.head()

,tam_loc,est_socio,clase_hog,sexo_jefe,edad_jefe,educa_jefe,tot_integ,hombres,mujeres,mayores,...,mater_serv,material,servicio,deposito,prest_terc,pago_tarje,deudas,balance,otras_erog,CVE_MUN
0,1,2,3,1,40,8,4,1,3,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2
1,1,2,1,1,83,8,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2
2,1,2,2,2,44,8,3,2,1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2
3,1,2,1,1,48,10,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,2
4,1,2,1,1,75,10,1,1,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,10327.86,0.0,0.0,2

In [7]:
df.tam_loc.dtype

dtype('int64')

In [8]:
df_copy = df.copy()

In [14]:
l = []
bandera = np.NAN
for column in df_copy.columns:
    if df_copy[column].dtype == np.int64:
        bandera = 'entero'
    elif df_copy[column].dtype == np.float64:
        bandera = 'flotante'
    else:
        bandera = 'otro'
        
    try:
        df_copy[column] =df_copy[column].astype('int64')
    except:
        l.append(column)
        
    print('COLUMNA: ', column)
    print('TIPO: ', bandera)
    print('NUNIQUE: ', df_copy[column].nunique())
    print('UNIQUE: ', df_copy[column].unique())
    print('VALUE COUNTS ', df_copy[column].value_counts())
    print('\n')

COLUMNA:  tam_loc
TIPO:  entero
NUNIQUE:  4
UNIQUE:  [1 2 3 4]
VALUE COUNTS  1    1665
2      36
4      17
3      15
Name: tam_loc, dtype: int64


COLUMNA:  est_socio
TIPO:  entero
NUNIQUE:  4
UNIQUE:  [2 3 4 1]
VALUE COUNTS  3    782
2    714
4    232
1      5
Name: est_socio, dtype: int64


COLUMNA:  clase_hog
TIPO:  entero
NUNIQUE:  5
UNIQUE:  [3 1 2 5 4]
VALUE COUNTS  2    999
3    435
1    277
5     15
4      7
Name: clase_hog, dtype: int64


COLUMNA:  sexo_jefe
TIPO:  entero
NUNIQUE:  2
UNIQUE:  [1 2]
VALUE COUNTS  1    1137
2     596
Name: sexo_jefe, dtype: int64


COLUMNA:  edad_jefe
TIPO:  entero
NUNIQUE:  78
UNIQUE:  [40 83 44 48 75 60 36 61 31 39 47 53 76 62 69 41 43 49 67 64 86 56 59 80
 51 55 82 66 81 30 50 28 87 37 42 68 32 54 35 65 58 94 52 85 84 72 73 77
 45 70 33 25 27 24 46 23 57 78 63 26 88 38 74 34 71 29 90 89 92 19 22 21
 91 79 95 18 96 20]
VALUE COUNTS  50    57
42    55
53    46
45    43
40    42
60    42
48    42
47    41
65    40
46    40
38    39
41    38
58    38
39    37
56    37
33    36
32    35
57    34
54    34
43    33
35    33
61    32
52    32
49    31
51    30
37    30
44    30
68    30
55    30
72    29
      ..
27    17
75    16
71    15
83    13
24    13
86    11
82    11
77    10
26     9
73     9
84     9
23     8
78     7
88     6
85     6
22     6
81     6
79     6
21     6
89     4
19     4
91     3
92     3
87     3
20     1
96     1
95     1
90     1
94     1
18     1
Name: edad_jefe, Length: 78, dtype: int64


COLUMNA:  educa_jefe
TIPO:  entero
NUNIQUE:  11
UNIQUE:  [ 8 10  4  6  7  1  3 11  9  5  2]
VALUE COUNTS  6     462
10    314
8     241
4     231
3     129
11     98
9      76
7      71
5      60
1      50
2       1
Name: educa_jefe, dtype: int64


COLUMNA:  tot_integ
TIPO:  entero
NUNIQUE:  13
UNIQUE:  [ 4  1  3  8  2  7  6  5  9 12 16 10 11]
VALUE COUNTS  4     395
3     383
2     334
1     276
5     192
6      73
7      40
8      21
9       8
10      6
12      3
16      1
11      1
Name: tot_integ, dtype: int64


COLUMNA:  hombres
TIPO:  entero
NUNIQUE:  9
UNIQUE:  [ 1  2  3  0  4  5 11  6  7]
VALUE COUNTS  1     711
2     485
0     243
3     213
4      52
5      21
6       5
7       2
11      1
Name: hombres, dtype: int64


COLUMNA:  mujeres
TIPO:  entero
NUNIQUE:  8
UNIQUE:  [3 0 1 6 2 4 5 7]
VALUE COUNTS  1    662
2    513
3    265
0    170
4     87
5     24
6      9
7      3
Name: mujeres, dtype: int64


COLUMNA:  mayores
TIPO:  entero
NUNIQUE:  11
UNIQUE:  [ 3  1  2  7  6  4  5 10  8 11  9]
VALUE COUNTS  2     540
3     423
4     301
1     296
5     115
6      32
7      16
8       6
11      2
10      1
9       1
Name: mayores, dtype: int64


COLUMNA:  menores
TIPO:  entero
NUNIQUE:  7
UNIQUE:  [1 0 2 4 3 5 6]
VALUE COUNTS  0    1152
1     333
2     198
3      39
5       5
4       5
6       1
Name: menores, dtype: int64


COLUMNA:  p12_64
TIPO:  entero
NUNIQUE:  11
UNIQUE:  [ 3  0  2  1  7  6  4  5  9  8 11]
VALUE COUNTS  2     523
3     359
1     301
4     264
0     149
5      94
6      28
7       7
8       5
9       2
11      1
Name: p12_64, dtype: int64


COLUMNA:  p65mas
TIPO:  entero
NUNIQUE:  5
UNIQUE:  [0 1 2 3 5]
VALUE COUNTS  0    1279
1     332
2     119
3       2
5       1
Name: p65mas, dtype: int64


COLUMNA:  ocupados
TIPO:  entero
NUNIQUE:  9
UNIQUE:  [2 0 1 3 4 7 5 8 6]
VALUE COUNTS  1    679
2    586
0    198
3    187
4     66
5     12
6      3
8      1
7      1
Name: ocupados, dtype: int64


COLUMNA:  percep_ing
TIPO:  entero
NUNIQUE:  11
UNIQUE:  [ 2  1  6  3  4  5  8  7 10  9  0]
VALUE COUNTS  2     607
1     475
3     390
4     178
5      49
6      20
7       5
8       4
9       2
0       2
10      1
Name: percep_ing, dtype: int64


COLUMNA:  perc_ocupa
TIPO:  entero
NUNIQUE:  9
UNIQUE:  [2 0 1 3 4 7 9 5 6]
VALUE COUNTS  1    703
2    579
0    198
3    180
4     60
5      8
6      3
9      1
7      1
Name: perc_ocupa, dtype: int64


COLUMNA:  ing_cor
TIPO:  entero
NUNIQUE:  1706
UNIQUE:  [41729 26190 34868 ... 97762 10961 23446]
VALUE COUNTS  34906     2
53701     2
26190     2
45820     2
130108    2
22475     2
59885     2
26999     2
83360     2
30590     2
29608     2
52081     2
59016     2
36590     2
36245     2
36505     2
38370     2
38314     2
22033     2
38906     2
289879    2
19615     2
46254     2
20448     2
64721     2
14797     2
40160     2
40267     1
25922     1
79180     1
         ..
115411    1
113786    1
56026     1
28280     1
31380     1
49811     1
160377    1
59544     1
6764      1
47726     1
78447     1
158320    1
12913     1
23154     1
35444     1
40510     1
29303     1
59635     1
47760     1
33403     1
109180    1
35030     1
43650     1
70275     1
19076     1
135817    1
51850     1
27276     1
41615     1
20480     1
Name: ing_cor, Length: 1706, dtype: int64


COLUMNA:  ingtrab
TIPO:  entero
NUNIQUE:  1314
UNIQUE:  [26729     0 19868 ... 52092 91956  3020]
VALUE COUNTS  0         187
11803       9
17704       7
17608       7
19076       6
14673       6
14086       5
35217       5
17900       4
5901        4
56065       4
15260       4
11739       4
7043        4
21130       4
8804        3
14163       3
23478       3
25826       3
36929       3
33934       3
36684       3
117391      3
10565       3
34239       3
24456       3
42309       3
33260       3
73369       3
29508       3
         ...
28839       1
113967      1
122160      1
58674       1
52532       1
13624       1
212282      1
17725       1
40254       1
100976      1
21798       1
28760       1
5380        1
13032       1
27909       1
29959       1
25865       1
13578       1
67866       1
54344       1
36114       1
122306      1
53168       1
27926       1
27929       1
9498        1
16845       1
34080       1
83386       1
5128        1
Name: ingtrab, Length: 1314, dtype: int64


COLUMNA:  trabajo
TIPO:  entero
NUNIQUE:  1136
UNIQUE:  [26729     0 19868 ... 15505 46711 91467]
VALUE COUNTS  0         330
11803      10
11739       9
17608       9
14673       8
17704       8
14086       7
7043        6
19076       6
35217       6
5901        5
21130       5
14754       5
29347       5
23233       5
42309       4
17900       4
11933       4
9782        4
25081       4
46467       4
21032       4
10565       4
56065       4
14163       4
16229       3
36684       3
24701       3
26413       3
15260       3
         ...
20107       1
167213      1
52524       1
27946       1
19180       1
21798       1
28760       1
148770      1
83386       1
34080       1
16845       1
55327       1
27929       1
15639       1
54344       1
21754       1
38157       1
13580       1
29962       1
25865       1
29959       1
21766       1
67499       1
138499      1
21762       1
21662       1
146005      1
68861       1
15612       1
13304       1
Name: trabajo, Length: 1136, dtype: int64


COLUMNA:  sueldos
TIPO:  entero
NUNIQUE:  648
UNIQUE:  [ 25745      0  19180  25081  27880  14576  24945   3130  10229  39590
  11739  42847  29803  26950   8704  41086  52532  23478  13206  14869
  37565   7630  14478   7826  58695  20543  36684 293478  17608  89502
  71602  54944  59668  53701  34524  64918  31868 126885  50163  24065
  33163  12326  14086 106229  49573  17704 442622  59016  22304  42554
  21032  84130  31278  35409  25180  88923  61630  33456  55760  17902
 261195 421508  99782  95469  29508   8852  38152  15540  24196  22131
  36590  20065  54293  29699  25967  16229  89999  26557  39836  42786
   3717  29347  32282  43728  55173  55467  27342  18195   8902   3815
  36978  23270   6563  11933  24786  47213  33639 146254  15344  28327
  30540  39245  11803  20655  41311  15737  46956  36097 117391  48130
  93913  44021  21130 258260  21423  26510   7336  17900  56799   5966
  39540 114456  35217   2950  18590   8262   9619  27737  32606  15934
  19956  52239  34630  11152   7483  25336  63342  19076  41380  70434
  41767  48928   9149  53602  27845  53114 162295  74836  14429  73369
  17364   8804  11699  13278  10327 119836 164347  22032  30098  11606
  16532  22010  10565  39130  11445  17119  15260  20788  41160  49402
 161104  44751  29834  23901  14754  44262   3540   1565  26413 212459
   5901  73770  19858  82173   7092  20901  16426  29755  23606 316956
  33260  48423   5478   3913  71902  79239  72696  21480  61309  32459
  20606   6147  11714  29985   4721  12717  32038  11093  10819   5282
   2641   2934  52972  36244  30815  25923  76304  25239  49157  34899
  16434  23867  22674   8353  35602  28918  25672   7377  89755  28032
  67278   2459  16721  16868   2005  14673  34923  36973  30245  35704
  37868  37131  19663   2347  29494  96847  76010  17315   6211  15847
  40108  31548  42364  16408   7160  25060  97967  59967  89021   1081
  25229  23967 120326 102717  65739 142336  10622  24590  28565   1222
  10271  33749  24358  31901  27293  41171  20635  38360  39619  17021
  11973  21836  36885  30983  97434 123260  26999  53413   4773  43756
  79672  55721  30688  20347   9782  49891  40032  39344  38262  16327
  39442  64565  44608  12590  17114  19565   1858   7043  49010  25359
  35204  51712  35801  58131  14163   8217  15147   4255  17706   2201
  21540  74249   9978  51945  39679  50718  19392  16945  12983  26360
  34043  21326   2445   9391   5869  56953  26336  18782  68086  10682
  31695  73093  34810  98453  20754  85721  48393  27029  69049  24668
  43229  66913  30125  30423  13695  15701  19369   3977  14917  19093
  30806  21717  67868  25770  45195  26119  56065   9836  52826  22499
  36391 104184 137934  27447 123934  10504  33049 132065  13842  61967
  75540  18295 237836 153442  31475  46369  51358  10584  61043 231847
 146739 190760  21154  25160 119337 327961  30727  88524  12913 103278
  72226  25826 154076  80706  26633  44999  39267  61336  20883  47734
  44852  26754  34229  34937  10858  38739 413114 176086  13597   3480
  34806  13127  69344  17395   3081   4918  35804  14331  66983  29999
  80853  22597  56347  11934  27149  16806  36767  33934  35755  21521
  40891  95673  45737   8114  12786  11498  88043  33652  24554   7081
  37770  34819  11005 150407  94426  85573  48688  46327  20152  15495
  42260  88630  39913  27586  67499  45646  14320  23311 100327  18880
  30521 155543  49304  17586  10868  46032  19573  21365   6195  28173
   2983  38187  28342  16032  70819  45934  19278  15639  22891  28467
   1173  24652  18885 220108  77771  66326 129130   4402 134254 104419
 163342  82622 118032  76721 185901  68967 132786 147540 184891  50995
  22375 128287  56685  12295  96393  22879 124728  57521 105652 234782
 203791 126195 152154 179005 149171  65635  16524  66032   9293  94499
  49597  37173  60163  16850  16309  72782  59576  29360  15789  59508
  16141  50771  43781  28740  15662   8950  25573 150491  97377  32754
  29754 140869 152461 134999   5163  27782  29934  83535  25241  46663
  51639  55920  77311  28760  32576  41869 225978   3668  56054 275869
 177049   7967   4891  25931 269999 205434 139891 114861  74585 383606
 196630  22426 274426  32262   6456  12393  43377  56641  29336  36782
  51652  20585  11535   4695  28967  17999  48983  30326  13891  40206
 152021   1027  24414  25856   5593  24098  29298 156521 121793  46622
  46467  10809  78847   8413  57727  17755  14380 122282  42165  37591
  21147  12708  16826  18978   2360    586  43434  23852   5065  11836
  26315  86022  65933   6573  53104  42065   9442 158478  98852  40721
  92445  22524   1790   4524   9546  20567  24309  15505]
VALUE COUNTS  0         355
17608      31
23478      24
11739      23
35217      22
29347      19
20543      17
14086      15
17704      15
14754      15
58695      14
14673      14
23606      13
11803      13
29508      13
20655      13
26413      12
11933      11
41086      10
59016      10
73369       9
47213       9
38152       9
117391      9
46956       8
41311       8
19076       8
88524       8
32282       8
64565       7
         ...
74836       1
124728      1
40032       1
97377       1
29803       1
19565       1
134254      1
19573       1
18978       1
27782       1
15495       1
25745       1
1173        1
97434       1
31901       1
7336        1
25770       1
40108       1
17586       1
15540       1
27845       1
1222        1
36973       1
11498       1
85721       1
95469       1
29934       1
126195      1
34043       1
150491      1
Name: sueldos, Length: 648, dtype: int64


COLUMNA:  horas_extr
TIPO:  entero
NUNIQUE:  82
UNIQUE:  [    0    97  5869  5901  2934    98  8804  3081  1760   489 17608  1173
  2445    99   745   590   149  1988   318   983  2508  2152  4426  4954
  7131   491  7043  6456   786   885   352   831   244   147   826   391
  3530  3521  2459  4972  4795   586 17016  3913  1467  2347  2054  1418
  4402  2950  1377   245  1672  8852 16721  2201  4206 14754  1907 11298
    73  8559  8606  8510 14673  1100 12786  5409  1770  1320  3619   440
 11933   733  1081   860   397   248    29   994  1267  2360]
VALUE COUNTS  0        1628
489         5
5901        3
5869        3
1760        3
1173        3
149         2
8852        2
397         2
2445        2
2934        2
4402        2
244         2
8804        2
97          2
1672        2
1467        2
3913        2
2152        1
2459        1
8606        1
14754       1
440         1
29          1
2508        1
73          1
2054        1
491         1
12786       1
2360        1
         ...
8510        1
5409        1
1320        1
1418        1
11298       1
3521        1
3530        1
14673       1
3619        1
11933       1
1770        1
1081        1
3081        1
17016       1
4954        1
4795        1
1907        1
745         1
786         1
826         1
831         1
860         1
994         1
4972        1
885         1
7043        1
2950        1
983         1
7131        1
733         1
Name: horas_extr, Length: 82, dtype: int64


COLUMNA:  comisiones
TIPO:  entero
NUNIQUE:  152
UNIQUE:  [    0 55573  5771 14673  4157 17900 14754  3521  8070  2934   489 11486
 28278  4108  2311  1760  7458  5999  5135 30081 59668 29347  3639   391
  7043  4475   590 11311  1967 33934  6147    34  5038  7605   983  9782
 34532  7972  2347  4027   786 14262  5624   250  1721  3374  1296  1173
   447 10081 11641 13940 12430 17213 27733  6505  4013 12885  3959   196
  4304   440 10565  4622  5508  7081 17704  1180  1467  1019  9944 10819
 23114  2298  2641  1858  7092  8804  3350 38852  7336  4940  2494  8852
  3442  1076  1711  5311    24  1663  1243 11803  7868  5869 17608  1868
 10327  4695    97 24652 10760  3423 14917  4426 32950 22375 22622  7454
 61160 44021 89021 24456  2054 15016  5820 27391  1057 11739  7131 20655
 11005  8559  2754  9586  4744  7777 81546 33442 31304 46740 27099 12717
  5901   929 12913 24945  7408  7573  4377  3179   190  1271 21521 10967
 26065  2274  3580  1790  6016  3913   836  2543]
VALUE COUNTS  0        1553
1173        4
14673       4
489         3
2347        3
983         3
5135        2
1180        2
5311        2
1711        2
17704       2
3423        2
1467        2
3639        2
2934        2
4426        2
590         2
7043        2
5901        2
4108        2
6147        2
4157        2
7972        2
8852        1
4744        1
12913       1
8804        1
196         1
24          1
4695        1
         ...
33934       1
3179        1
27733       1
1076        1
1057        1
26065       1
21521       1
1019        1
44021       1
4027        1
89021       1
7092        1
1243        1
11486       1
7408        1
1271        1
1296        1
3350        1
7454        1
7458        1
3374        1
3442        1
11641       1
30081       1
5508        1
7573        1
7605        1
3521        1
2298        1
7131        1
Name: comisiones, Length: 152, dtype: int64


COLUMNA:  aguinaldo
TIPO:  entero
NUNIQUE:  337
UNIQUE:  [  983     0   688  1056   978   489   440   245  2262  1229   737  1540
   244   586  2274   122  2445  1711  6114   733  3729  2734  1988  2486
 12786  8360  2005  1100  1173  2950 29508  2459   611  2934   885  1106
  1475  4720   366 51358 35461 12228  7336 26104  3614  5380  2827  7008
  6516  1032  2567   391  2201  2690  1467  3668  1834   880  3179  4157
   298  1844  1377  2339  4891  4303  3913 11005  4010  3423  1956 48913
  1222   116  3688    86   614   209  2114   555  1589  1614   146  1296
   635  1736 14673  1864 19889   745  4918  1499   147 11249   994  1740
   934 40819  6393 20543   491   959   196 12961  5869  9048  2299   870
   546  1155  1352  3442  1785 14184  4279    85   256 39130  2152  2287
   372  4350  1721  2803  1967  1081  2286  1394  2983  2127  3766   422
  1243 10081  7377  4206  1883  3196 15407  9293  2323  4402  4548  5624
  3853  4426  2078  4524 10271  8559   660  1345   124  1491   418  2901
  3301   540   786  6847  1663  1258  1096  1080  1051  1549  3934   990
  3306   831   171   342  2788  8804  2436  5966  1057 11812  2213   929
  7131   221  2494  1418   795  2090   442   513   368  1858  3332   855
  9782   410 10278  8016  2704  9836  1638 19565 10193 22872    68   538
   827  7581   195  1124  3103  2088  1438 15983    73  4646  1143  4102
 14262   754    48   183  4769  2812   317   269   621   845   172   782
  5820  8070   464  7955  1573  6762 20005  5286   860  3057   565  6603
  3604  2361  8606  6358  8192   435 21754  9447 11803  1598 10819 15652
 12295 38152 18342 26168  2235  2796 14257  3928  4672  7622  2859 15591
 16508  2396 16019 26080 17119  8491 10516  1426  2581  1797  4597 10760
 26413  2103   497  4180  1413  3081  5655  1367 10696 13770 12717 20298
  4723  9342  3232  6215   562  5114  1907  7092   165  3977  1715  7831
  3319  2470 15737  5901  9344   590 11557 36684 61475 13940 13524  2606
  3228   684  1320   596  4057  1180  1131  1063  5991   944   749  1795
   807   293  2163  1770  5163   758    99  7209  7060  1290  5040  1524
  6970]
VALUE COUNTS  0        814
489       26
2445      25
1467      22
978       21
1229      20
1222      19
733       18
1956      17
983       16
737       14
4891      14
611       13
491       12
244       12
1711      12
2201      11
366       11
1475      11
2459      10
1967      10
2934       9
1721       9
3668       8
368        7
7336       7
1345       7
2690       7
2950       6
860        6
        ...
7955       1
4672       1
2812       1
1715       1
2827       1
786        1
990        1
7131       1
26168      1
1598       1
959        1
7092       1
944        1
2470       1
934        1
1638       1
5040       1
7060       1
13940      1
885        1
7008       1
16019      1
5901       1
2901       1
29508      1
827        1
6970       1
7831       1
2859       1
1907       1
Name: aguinaldo, Length: 337, dtype: int64


COLUMNA:  indemtrab
TIPO:  entero
NUNIQUE:  27
UNIQUE:  [     0     17     19     27  10760   4180  17213  21521   2016    205
    733   9782   1180   2754  31967     69    646  29508    737  12295
  11739  73369 219130   5869   3913   4972   5966]
VALUE COUNTS  0         1704
17           2
19           2
9782         2
737          1
12295        1
27           1
69           1
4180         1
205          1
10760        1
646          1
2754         1
733          1
219130       1
2016         1
29508        1
4972         1
21521        1
1180         1
31967        1
11739        1
73369        1
5869         1
3913         1
5966         1
17213        1
Name: indemtrab, dtype: int64


COLUMNA:  otra_rem
TIPO:  entero
NUNIQUE:  156
UNIQUE:  [    0  1327   245  1475  4402   635  2995   855 14673  4891  1467  3977
  1278 40108  1100  6393  1967  2934  2494  4127   393  2445  1369   983
  3228   293  3521   596  5022  2386   880 27348   994   295  6637  1799
  6456 18586  6847  3081    99   344  9836   342 28858  1988  9782 15701
   737  4180   391  2788 11803   684  3179  1711   978  1222  2005   586
  1956  5086  1809  5331  1273  2459  2883  1526  5967  2950  4108   489
   149  2535 14086  1565  7630  5869 10271  3442   491  1106  2337  1491

In [11]:
l

[]

In [17]:
df_copy.drop(labels=['CVE_MUN'], axis=1, inplace=True)

In [18]:
file = '../../../../../../../dataframes/enigh/CONCENTRADOHOGAR/mixed/df_09_clean.csv'

In [19]:
df_copy.to_csv(file,index = False, header = True, sep = ',', encoding = 'utf-8')